name: s2s2net
channels:
  - conda-forge
dependencies:
  - conda-forge::jupyterlab=3.2.9
  - conda-forge::pandas=1.4.1
  - conda-forge::python=3.9.10
  - conda-forge::pytorch=1.10.0
  - conda-forge::pytorch-lightning=1.5.10
  - conda-forge::torchgeo=0.2.0
